08/11/21 (20:40:29) | ERROR: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
Traceback (most recent call last):
  File "/home/maker/.local/lib/python3.9/site-packages/bpytop.py", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
09/11/21 (01:46:07) | ERROR: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
Traceback (most recent call last):
  File "/home/maker/.local/lib/python3.9/site-packages/bpytop.py", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
09/11/21 (17:55:14) | ERROR: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
Traceback (most recent call last):
  File "/home/maker/.local/lib/python3.9/site-packages/bpytop.py", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/maker/.config/bpytop/themes'
